import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/template/Header";
import Footer from "../components/template/Footer";
import BottomBar from "../components/template/BottomBar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} font-['Hind_Siliguri'] bg-white text-slate-900`}
                // Adding this here suppresses the warning caused by browser extensions 
                // modifying attributes on the body tag (like ColorZilla)
                suppressHydrationWarning
            >
                <Header />
                <main className="min-h-screen">{children}</main>
                <Footer />
                <BottomBar />
            </body>
        </html>
    );
}